# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Not A Single Fuck Given
email: RuneDSG@Gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Providing weak memes and not giving half a fuck since 1999. -TryHardRune -Ryan
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://Notasinglefuckgiven.com" # the base hostname & protocol for your site
twitter_username: n/a
github_username: n/a

# Build settings
markdown: kramdown
